version: ~> 1.0
language: java
addons:
  apt:
    packages:
    - xvfb
before_install:
  - export M2_HOME=$HOME/apache-maven-3.5.0
  - "travis/before-install-$BUILD_SYSTEM"
  - export PATH=$M2_HOME/bin:$PATH
install: "travis/install-$BUILD_SYSTEM"
script:
  - export AUTH_TOKEN
  - export GH_TOKEN
  - "travis/script-$BUILD_SYSTEM"
before_cache: "travis/before-cache-$BUILD_SYSTEM"
after_success: "travis/after-success-$BUILD_SYSTEM"
cache:
  directories:
  - "$HOME/.goomph"
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
  - "$HOME/.m2"
  - "$HOME/apache-maven-3.5.0"
env:
  global:
    - BUILD_SYSTEM=gradle
    - secure: KcugjQYnBqeZ7XenZD5QY7jhekVPO0QpQyjDUteLytaokhyRK2g6eNvr/pPerN2uWUvsPwO18P9F+oOupge1cpPZf4cEY8RzLIromyUoRWd6JA0SKciUYdN2kSqnC4uZSJGXeGLoroyEEL4Q2sqimpkbIGxgxYtVniWgJULOyR4=
    - secure: jacvGPYX4ugG/HgwJEEpWnllWsS/ipX+qRJ7qM5mbDYryeqsz0eiaxBxQ6IpDyj0v6O4DUi74lSQs/UxCWcUxvOn/5AweCZfoF1U8vt1xivanR4MbC2kr6rJ6ohICuJ4PHDS4IffncgaP3Y8cfExHq6+d0tbibYkjRIiMUGpSik=
    - secure: "BQZTbI/fcMs6h8SIoAFZWGvrKNM3Yp+w1WGjBEpwt+YgRGkpG+Z6CejML4yTNwsic8qOKJDVexW2gZwOylQkGc6D/czsTMs7aIOc+SnkqD0IWgIXJ9kz3aN5liAvIqOqUtrfKmQfJdI3ZdOQcWvbufaiD532hIsE03a47oNt1O8="
    - secure: "CQCKoejOt96qiDOBOF4X/EUGdgeB/IG+ObjMhbBP7cimnqug9MpFe+5IaNhsAt10cBFdopOS29JpDvoPdinAIJpblkAR8rUG9eU587bknU7Z7lvuXRaSELot3jNEweoGxXMx9nEMFcf2eBy6RncWxtLU4/3BqI9VCfijIrqCULg="
jobs:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk8
      env: BUILD_SYSTEM=maven
    - os: linux
      jdk: openjdk11
    - os: osx
      osx_image: xcode9.3  # Java 1.8
    - os: osx
      osx_image: xcode9.4  # Java 13
