[versions]
eclipse = "4.21.0"
eclipse-wst-jsdt = "1.0.201.v2010012803"
google-java-format = "1.7"
ktfmt = "0.42"
spotless = "6.13.0"

[libraries]
android-tools = "com.android.tools:r8:2.2.42"
ant = "org.apache.ant:ant:1.10.12"
commons-cli = "commons-cli:commons-cli:1.5.0"
commons-io = "commons-io:commons-io:2.11.0"
dexlib2 = "org.smali:dexlib2:2.5.2"
eclipse-ecj = "org.eclipse.jdt:ecj:3.21.0"
eclipse-osgi = "org.eclipse.platform:org.eclipse.osgi:3.17.0"
eclipse-wst-jsdt-core = { module = "org.eclipse.wst.jsdt:core", version.ref = "eclipse-wst-jsdt" }
eclipse-wst-jsdt-ui = { module = "org.eclipse.wst.jsdt:ui", version.ref = "eclipse-wst-jsdt" }
errorprone-core = "com.google.errorprone:error_prone_core:2.18.0"
gradle-download-task = "de.undercouch:gradle-download-task:5.3.0"
gradle-errorprone-plugin = "net.ltgt.gradle:gradle-errorprone-plugin:3.0.1"
gradle-spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
gson = "com.google.code.gson:gson:2.10"
guava = "com.google.guava:guava:31.1-jre"
hamcrest = "org.hamcrest:hamcrest:2.2"
htmlparser = "nu.validator.htmlparser:htmlparser:1.4"
java_cup = "java_cup:java_cup:0.9e"
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version = { strictly = "1.3.2" } }
jericho-html = "net.htmlparser.jericho:jericho-html:3.2"
json = "org.json:json:20220924"
jspecify = "org.jspecify:jspecify:0.3.0"
junit = "junit:junit:4.13.2"
nullaway = "com.uber.nullaway:nullaway:0.10.7"
rhino = "org.mozilla:rhino:1.7.14"
slf4j-api = "org.slf4j:slf4j-api:2.0.6"
w3c-css-sac = "org.eclipse.birt.runtime:org.w3c.css.sac:1.3.1.v200903091627"

[plugins]
eclipse-mavencentral = "com.diffplug.eclipse.mavencentral:3.40.0"
file-lister = "all.shared.gradle.file-lister:1.0.2"
google-java-format = "com.github.sherter.google-java-format:0.9"
jarTest = "com.github.hauner.jarTest:1.0.1"
kotlin-jvm = "org.jetbrains.kotlin.jvm:1.8.0"
ktfmt = "com.ncorti.ktfmt.gradle:0.11.0"
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
task-tree = "com.dorongold.task-tree:2.1.1"
versions = "com.github.ben-manes.versions:0.44.0"
